version: "3.9"

services:
  backend:
    build: ./backend
    container_name: fire-backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules   # 👉 mantiene los node_modules internos del contenedor
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    container_name: fire-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules   # 👉 igual que el backend
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
